import os
import numpy as np


class ReplayStore:
    #Circular buffer that stores training examples generated by self-play.

    #Each example is a triple:
    #    board_tensor:   (6, 8, 8) float32 — encoded board state
    #    policy:         (65,)     float32 — MCTS visit distribution
    #    value:          (1,)      float32 — game outcome from that player's view

    #The buffer is stored on disk as a compressed .npz file so training
    #can resume after a crash or restart without replaying all games.
    #A maximum size is enforced — when full, oldest examples are dropped.
    

    def __init__(self, max_size: int = 500_000, save_path: str = "data/replay_buffer/buffer.npz"):
        self.max_size  = max_size
        self.save_path = save_path

        self.boards   = []
        self.policies = []
        self.values   = []

        os.makedirs(os.path.dirname(save_path), exist_ok=True)

    def push(self, board_tensor, policy: np.ndarray, value: float):
        # Add one training example to the buffer.
        self.boards.append(board_tensor.numpy() if hasattr(board_tensor, 'numpy') else board_tensor)
        self.policies.append(policy.astype(np.float32))
        self.values.append(np.array([value], dtype=np.float32))

        # Enforce max size by dropping oldest entries
        if len(self.boards) > self.max_size:
            self.boards.pop(0)
            self.policies.pop(0)
            self.values.pop(0)

    def push_game(self, trajectory: list):
        #Add all positions from one complete game.

        #Args:
        #    trajectory: list of (board_tensor, policy, value) triples
        #                as returned by SelfPlayWorker.play_one_game()
        
        for board_tensor, policy, value in trajectory:
            self.push(board_tensor, policy, value)

    def sample(self, batch_size: int):
        #Sample a random minibatch from the buffer.

        #Returns:
        #    boards:   np.ndarray (batch, 6, 8, 8)
        #    policies: np.ndarray (batch, 65)
        #    values:   np.ndarray (batch, 1)
        
        n = len(self.boards)
        assert n >= batch_size, f"Buffer has {n} examples, need {batch_size}"

        indices = np.random.choice(n, batch_size, replace=False)
        boards   = np.stack([self.boards[i]   for i in indices])
        policies = np.stack([self.policies[i] for i in indices])
        values   = np.stack([self.values[i]   for i in indices])
        return boards, policies, values

    def __len__(self):
        return len(self.boards)

    def save(self):
        # Persist the buffer to disk as a compressed numpy archive.
        if len(self.boards) == 0:
            print("[ReplayStore] Buffer is empty, nothing to save.")
            return
        np.savez_compressed(
            self.save_path,
            boards   = np.stack(self.boards),
            policies = np.stack(self.policies),
            values   = np.stack(self.values),
        )
        print(f"[ReplayStore] Saved {len(self.boards):,} examples to {self.save_path}")

    def load(self):
        # Load a previously saved buffer from disk.
        if not os.path.exists(self.save_path):
            print("[ReplayStore] No existing buffer found, starting fresh.")
            return
        data = np.load(self.save_path)
        self.boards   = list(data['boards'])
        self.policies = list(data['policies'])
        self.values   = list(data['values'])
        print(f"[ReplayStore] Loaded {len(self.boards):,} examples from {self.save_path}")